-
  name: "First Playbook"
  hosts: all
  tasks:
    -
      name: "Installing vsftpd package in Client Machine"
      apt: name="vsftpd" state=present

    -
      name: "Installing tree package in Client Machine"
      apt: name="tree" state=present

    -
      name: "uninstalling nginx package in Client Machine"
      apt: name="nginx" state=absent