-
  name: "First Playbook"
  hosts: all
  vars:
    var1: var1
    var2: var2
    var3: var3
    var4: var4
    var5: var5
    var6: var6
    var7: var7
    var8: var8
    var9: var9
    var10: var10
    var11: var11
    var12: var12
  tasks:
    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var1 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var2 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var3 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var4 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var5 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var6 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var7 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var8 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var9 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var10 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var11 }}.txt

    -
      name: "Creating file in Client Machine"
      command: touch /tmp/{{ var12 }}.txt