- name: Test Connectivity
  hosts: web
  vars:
    ansible_ssh_pass: "{{ lookup('csvfile', 'web file=cred.csv delimiter=,') }}"
  tasks:
    - name: create a dummy file on webserver
      command: touch /tmp/csv_lookups.txt
