-
  name: "First Playbook"
  hosts: all
  vars:
    age: 5
  tasks:
    -
      name: "Starting Particular mention service"
      condition: touch /tmp/file.txt
      when: age == 10

    -
      name: "Starting Particular mention service"
      condition: touch /tmp/dev.txt
      when: age > 10

    -
      name: "Starting Particular mention service"
      condition: touch /tmp/qa.txt
      when: age < 10