-
  name: "First Playbook"
  hosts: all
  tasks:
    -
      name: "Execute Script in Client Machine"
      script: script.sh user1           # Here User1 is Arguments


-
  name: "Second Playbook"
  hosts: all
  tasks:
    -
      name: "Execute Script in Client Machine"
      script: script.sh user1  remove=/tmp/test.txt chdir=/home       # Here User1 is Arguments
