-
  name: "First Playbook"
  hosts: all
  tasks:
    -
      name: "Installing vsftpd package in Client Machine"
      apt: name="{{ items }}" state=present
      with_items:
        - vsftpd
        - httpd
        - nginx
        

-
  name: "First Playbook"
  hosts: all
  tasks:
    -
      name: "Installing vsftpd package in Client Machine"
      user: name="{{ item }}" state=present
      loop:
        - user1
        - user2
        - user3
        